### ISSUE TITLE
Can't read property 'author ' of undefined

### ISSUE THREAD

**Issue by johachi-dw** [baijunyao/action-slack-notify#2]
I'm using the following code to get slack notifications, but get an error. Do you know what I'm doing wrong?

**Code**
```
name: Lint-check

on:
  pull_request:
    branches: 
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Front-end Dependencies
      run: yarn

    - name: Check Linting
      run: yarn prettier --check "src/**/*.js" "functions/**/*.ts"

    - name: Build Front-end
      run: yarn build

    - name: Build Firebase Back-end
      run: |
        cd functions
        npm install
        npm run build

    - name: Notify slack
      uses: baijunyao/action-slack-notify@master
      if: always()
      with:
        channel: GTF7J72LQ
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        github_context: ${{ toJson(github) }}
        job_context: ${{ toJson(job) }}
```

**Error**
```
TypeError: Cannot read property 'author' of undefined
    at /home/runner/work/_actions/baijunyao/action-slack-notify/master/lib/main.js:46:71
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/baijunyao/action-slack-notify/master/lib/main.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/baijunyao/action-slack-notify/master/lib/main.js:3:12)
    at run (/home/runner/work/_actions/baijunyao/action-slack-notify/master/lib/main.js:21:12)
    at Object.<anonymous> (/home/runner/work/_actions/baijunyao/action-slack-notify/master/lib/main.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
##[error]Cannot read property 'author' of undefined
##[error]Node run failed with exit code 1
```
